### 直接切换协程

这里的切换是指将协程对应的 Task 数据结构的指针给到 `a0` 寄存器，并且将 `pc` 寄存器指向执行函数，协程执行还是需要在高级语言中使用 `Rust` 提供的 `poll` 函数完成。

```rust
#![no_std]
#![no_main]
use macros::main;
use executor::Task;
#[main]
pub async fn main() -> i32 {
    let task = Task::new(Box::new(test(23)), 0, executor::TaskType::Other);
    unsafe {
        let raw_task = Arc::into_raw(task.clone()) as usize;
        let exec_fn = execute as usize;
        core::arch::asm!(
            "jalr t0",
            in("a0") raw_task,
            in("t0") exec_fn,
        );
        println!("back");
        let raw_task = Arc::into_raw(task) as usize;
        core::arch::asm!(
            "jalr t0",
            in("a0") raw_task,
            in("t0") exec_fn,
        );
    }    
    0
}

async fn test(a: usize) -> i32 {
    let mut help = Box::new(Help(false));
    help.as_mut().await;
    println!("into test {}", a);
    0
}
struct Help(bool);
impl Future for Help {
    type Output = i32;
    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> core::task::Poll<Self::Output> {
        if !self.0 {
            self.0 = true;
            core::task::Poll::Pending
        } else {
            core::task::Poll::Ready(0)
        }
    }
}
use executor::waker;
use core::task::Context;
use alloc::sync::Arc;
use core::pin::Pin;
pub fn execute(task: *const Task) {
    unsafe {
        let task = Arc::from_raw(task);
        let waker = waker::from_task(task.clone());
        let mut cx = Context::from_waker(&waker);
        let fut = &mut *task.fut.as_ptr();
        let mut future = Pin::new_unchecked(fut.as_mut());
        match future.as_mut().poll(&mut cx) {
            core::task::Poll::Ready(_) => println!("ok"),
            core::task::Poll::Pending => println!("pending"),
        }
    }
}
```

`main` 协程中两次使用汇编跳转到协程执行函数，中间如果不加打印的语句，会出现奇怪的地址非对齐错误。见下。

```bash
Rust user shell
>> switch
pending
[core 1][ERROR] os/src/trap/mod.rs:120 Unsupported trap Exception(StoreMisaligned), stval = 0xfffffffffffffff1!
```

如果使用了打印函数，则能够正常执行，不清楚原因。

```bash
Rust user shell
>> switch
pending
back 3
into test 23
ok
```

出现这种可能的原因，可能是因为直接用汇编跳转，导致函数栈没有清空，从而出现了非对齐地址访问。如果将栈清空，应该不会出现这个错误，这里使用 `println` 打印，也会对栈产生影响，所以可能导致了第二次能够运行成功。

但这个测试可以证明，利用硬件进行切换（指从上个协程结束到选出下一个就绪协程，因为协程的执行与普通的函数调用区别不大，所以不应该处理上下文保存和恢复）是具有可行性的。

